name: Check SSH Connection with Password

on:
  push:
    branches:
      - main

jobs:
  check-ssh:
    name: Check SSH Connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check SSH Connection
        run: |
          sshpass -p  ssh -p 22 @43.231.127.206 echo "SSH connection successful"
        env:
          SSHPASS: 11
