name: Debug Workflow

on:
  push:
    branches:
      - main

jobs:
  debug:
    runs-on: ubuntu-latest

    steps:
      - name: Debug Networking
        run: |
          ping -c 5 google.com
          traceroute google.com
          nslookup google.com
          curl -I https://www.google.com
          wget https://www.google.com
