
name: Check Open Ports on GitHub Runner

on:
  push:
    branches: [ main ]

jobs:
  check-ports:
    name: Check Ports
    runs-on: ubuntu-latest
    steps:
      - name: Check Common Ports
        run: |
          for port in {80,443,22,8080}; do
            nc -zv localhost $port
            if [ $? -eq 0 ]; then
              echo "Port $port is open on GitHub runner."
            else
              echo "Port $port is not open on GitHub runner."
            fi
          done
