name: Check SSH Port

on:
  push:
    branches:
      - main

jobs:
  check-ssh-port:
    name: Check SSH Port
    runs-on: ubuntu-latest

    steps:
      - name: Check SSH Port
        run: |
          nc -zv 24.199.117.95 22
