
name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'main'
      - name: Check Port 80 on 43.231.127.206
        run: |
          nc -zv 43.231.127.206 80
          if [ $? -eq 0 ]; then
            echo "Port 80 is open on 43.231.127.206. The web server is responding."
          else
            echo "Port 80 is not open on 43.231.127.206. The web server is not responding."
          fi

