name: Check Open Ports

on:
  push:
    branches:
      - main

jobs:
  check-ports:
    name: Check Ports
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install nmap
        run: sudo apt-get update && sudo apt-get install -y nmap

      - name: Scan Ports
        run: nmap -p 1-65535 localhost
