name: Check SSH Connection

on:
  push:
    branches:
      - main

jobs:
  check-ssh:
    name: Check SSH Connection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check SSH Connection
        run: |
          ssh -o "StrictHostKeyChecking no" -o "BatchMode yes" -p 22 root@43.231.127.206 echo "SSH connection successful"
