name: Deploy test file on server 

on:
  push:
    branches:
      - main

jobs:

  deploy-main-server:
    if: github.ref == 'refs/heads/main'
    runs-on: sample123-runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: copy file
        run: |
          ls
          pwd
          
